all: clean comp run

clean:
	rm -rf ./*.exe ./*~
comp:
	gcc -Wall -g -o parameterEvaluation_POC.exe parameterEvaluation_POC.c

run:
	./parameterEvaluation_POC.exe # program receives no imput
